# Generated by Django 5.0.3 on 2026-06-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='自习室编号')),
                ('name', models.CharField(max_length=80, verbose_name='自习室名称')),
                ('location', models.CharField(max_length=120, verbose_name='位置')),
                ('open_hours', models.CharField(max_length=40, verbose_name='开放时间')),
                ('facilities', models.JSONField(default=list, verbose_name='设施')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '自习室',
                'verbose_name_plural': '自习室',
                'db_table': 'rooms',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True, verbose_name='账号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('role', models.CharField(choices=[('student', '学生'), ('admin', '管理员')], default='student', max_length=16, verbose_name='角色')),
                ('college', models.CharField(max_length=80, verbose_name='学院')),
                ('class_name', models.CharField(max_length=80, verbose_name='班级')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=12, verbose_name='座位号')),
                ('status', models.CharField(choices=[('free', '空闲'), ('used', '已占用'), ('booked', '已预约'), ('maintenance', '维修')], default='free', max_length=16, verbose_name='状态')),
                ('position_note', models.CharField(max_length=80, verbose_name='位置说明')),
                ('config', models.CharField(max_length=120, verbose_name='配置')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.room')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'db_table': 'seats',
                'ordering': ['room__sort_order', 'seat_no'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待签到'), ('checked_in', '已签到'), ('completed', '已签退'), ('canceled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.room')),
                ('seat', models.ForeignKey(db_column='seat_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.seat')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.user')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'db_table': 'bookings',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40, verbose_name='违规类型')),
                ('reason', models.CharField(max_length=200, verbose_name='原因')),
                ('status', models.CharField(default='已处理', max_length=20, verbose_name='状态')),
                ('happened_at', models.DateTimeField(verbose_name='发生时间')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='booking.user')),
            ],
            options={
                'verbose_name': '违规记录',
                'verbose_name_plural': '违规记录',
                'db_table': 'violations',
                'ordering': ['-happened_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'seat_no'), name='uniq_room_seat'),
        ),
    ]
